<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE help [
<!ENTITY lt "#38;#60;">
<!ENTITY gt "&#62;">
<!ENTITY amp "&#38;#38;">
<!ELEMENT help (name , synopsis , description , arguments+ , outputs* , example* , bugs* , references*, reporting* , see-also*)*>
<!ELEMENT name (#PCDATA)>
<!ELEMENT synopsis (#PCDATA)>
<!ELEMENT description (#PCDATA)>
<!ELEMENT arguments (positional* , required-flagged* , optional-flagged*)*>
<!ELEMENT positional (intro* , argument* , explanation*)*>
<!ELEMENT required-flagged (intro* , argument* , explanation*)*>
<!ELEMENT optional-flagged (intro* , argument* , explanation*)*>
<!ELEMENT intro (#PCDATA)>
<!ELEMENT argument (#PCDATA)>
<!ELEMENT explanation (#PCDATA)>
<!ELEMENT outputs (output* , explanation*)>
<!ELEMENT output (#PCDATA)>
<!ELEMENT example (#PCDATA)>
<!ELEMENT references (#PCDATA)>
<!ELEMENT bugs (#PCDATA)>
<!ELEMENT reporting (#PCDATA)>
<!ELEMENT see-also (#PCDATA)>
]>

<help>
	<name>mri_normalize</name>
	<synopsis>mri_normalize &lt;input vol&gt; &lt;output vol&gt;</synopsis>
	<description>Normalize the white-matter, optionally based on control points. The input volume is converted into a new volume where white matter image values all range around 110.</description>
  <arguments>
    <positional>
      <argument>&lt;input vol&gt;</argument>
      <explanation>input mri volume file</explanation>
      <argument>&lt;output vol&gt;</argument>
      <explanation>output mri volume file</explanation>
    </positional>
    <required-flagged>
      <intro>None</intro>
    </required-flagged>
    <optional-flagged>
      <argument>-n &lt;int n&gt;</argument>
      <explanation>use n 3d normalization iterations (default=2)</explanation>
      <argument>-no1d</argument>
      <explanation>disable 1d normalization</explanation>
      <argument>-nonmax_suppress (1/0)</argument>
      <explanation>turn non-maximum suppression on (1) or off (0) when using interior of surfaces</explanation>
      <argument>-conform</argument>
      <explanation>interpolate and embed volume to be 256^3</explanation>
      <argument>-noconform</argument>
      <explanation>do not conform the volume</explanation>
      <argument>-gentle</argument>
      <explanation>perform kinder gentler normalization</explanation>
      <argument>-f &lt;path to file&gt;</argument>
      <explanation>use control points file (usually control.dat)</explanation>
      <argument>-fonly &lt;fname&gt;</argument>
      <explanation>use only control points file</explanation>
      <argument>-lonly &lt;fname&gt;</argument>
      <explanation>use only control points in label file</explanation>
      <argument>-label &lt;fname&gt;</argument>
      <explanation>use control points in label file</explanation>
      <argument>-w &lt;mri_vol c&gt; &lt;mri_vol b&gt;</argument>
      <explanation> write ctrl point(c) and bias field(b) volumes</explanation>
      <argument>-a &lt;float a&gt;</argument>
      <explanation>use control point with intensity a above target (default=25.0)</explanation>
      <argument>-b &lt;float b&gt;</argument>
      <explanation>use control point with intensity b below target (default=10.0)</explanation>
      <argument>-g &lt;float g&gt;</argument>
      <explanation>use max intensity/mm gradient g (default=1.000)</explanation>
      <argument>-prune &lt;boolean&gt;</argument>
      <explanation>turn pruning of control points on/off (default=off). pruning useful if white is expanding into gm</explanation>
      <argument>-MASK maskfile</argument>
      <argument>-atlas &lt;path to gca&gt;&lt;path to gca transform&gt; &lt;min distance of control points from non-brain&gt;</argument>
      <explanation>use atlas to exlude control-points from being in non-brain regions</explanation>
      <argument>-noskull</argument>
      <argument>-monkey</argument>
      <explanation>turns off 1d, sets num_3d_iter=1</explanation>
      <argument>-nosnr</argument>      
      <explanation>disable snr normalization</explanation>
      <argument>-sigma sigma</argument>
      <explanation>smooth bias field</explanation>
      <argument>-aseg aseg</argument>
      <argument>-v Gvx Gvy Gvz</argument>
      <explanation>for debugging</explanation>
      <argument>-d Gx Gy Gz</argument>
      <explanation>for debugging</explanation>
      <argument>-r controlpoints biasfield</argument>
      <explanation>for reading</explanation>
      <argument>-surface &lt;surface&gt; &lt;xform&gt;</argument>
      <explanation>normalize based on the skelton of the interior of the transformed surface</explanation>
      <argument>-u or -h</argument>
      <explanation>print usage</explanation>
 </optional-flagged>
  </arguments>
	<example>mri_normalize SUBJECT/mri/nu.mgz SUBJECT/mri/T1.mgz

Uses the nu volume (nonuniformity corrected volume), and creates the T1 volume, with white matter voxels around 110 image value</example>
	<example>mri_normalize -noskull -aseg aseg.mgz -mask brainmask.mgz norm.mgz brain.mgz

Uses the norm volume, and creates the brain volume, making use of the aseg and masking with brainmask</example>
  <references>"Cortical Surface-Based Analysis I: Segmentation and Surface Reconstruction", Dale, A.M., Fischl, B., Sereno, M.I. (1999) NeuroImage 9(2):179-194
</references>
  <reporting>Report bugs to &lt;freesurfer@nmr.mgh.harvard.edu&gt;</reporting>
	<see-also>nu_correct, mri_fill</see-also>
</help>
